# Generated by Django 3.2.12 on 2022-05-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_myuser_is_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_email_verified',
            field=models.BooleanField(null=True),
        ),
    ]
