# Generated by Django 3.2.12 on 2022-03-18 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='module',
            name='year_of_study',
        ),
        migrations.CreateModel(
            name='CourseModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_study', models.PositiveIntegerField(null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.course')),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.module')),
            ],
        ),
        migrations.AddConstraint(
            model_name='coursemodules',
            constraint=models.UniqueConstraint(fields=('course_id', 'module_id'), name='unique_course_modules'),
        ),
    ]
